### PR TITLE
ui: bottom navigations for patient and doctor + refactored file and class names

### PR DESCRIPTION
**Pull request by rchtgpt**
## Doctor Home
</img>

_TODO: Doctor Profile_

## Patient Home
</img>
</img>

### CODE REVIEW

**Comment by rchtgpt** [comment]
@all-contributors please add @dotrachit for development ✨

**Comment by rchtgpt** [comment]
@all-contributors please add @dotrachit for code

**Comment by dotrachit** [comment]
@all-contributors please add @dotrachit for design, @Ajitesh13 for code, and @Imperial-lord for code.

**Comment by dotrachit** [comment]
sorry @all-contributors,  please add @dotrachit for design and code.

**Comment by rchtgpt** [comment]
@all-contributors, please add @dotrachit for design and code.

**Comment by rchtgpt** [comment]
@all-contributors, please add @Imperial-lord  for code.

**Pull request merged**
